//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckUpCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CheckUpCard()
        {
            this.JobCards = new HashSet<JobCards>();
        }
    
        public int Id { get; set; }
        public Nullable<int> InitContId { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsOpen { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<int> AddedUserId { get; set; }
        public Nullable<int> AddedMechanicId { get; set; }
        public Nullable<int> MaintenanceTypeId { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual InitialControlSchedule InitialControlSchedule { get; set; }
        public virtual MaintenanceType MaintenanceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobCards> JobCards { get; set; }
    }
}
