//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BBServiceEntities : DbContext
    {
        public BBServiceEntities()
            : base("name=BBServiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actions> Actions { get; set; }
        public virtual DbSet<Companies> Companies { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<NotificationContent> NotificationContent { get; set; }
        public virtual DbSet<NotificationTitles> NotificationTitles { get; set; }
        public virtual DbSet<Operations> Operations { get; set; }
        public virtual DbSet<Permissions> Permissions { get; set; }
        public virtual DbSet<Positions> Positions { get; set; }
        public virtual DbSet<Routes> Routes { get; set; }
        public virtual DbSet<Sectors> Sectors { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Vehicles> Vehicles { get; set; }
        public virtual DbSet<VehiclesBrand> VehiclesBrand { get; set; }
        public virtual DbSet<AggregatedCounter> AggregatedCounter { get; set; }
        public virtual DbSet<Counter> Counter { get; set; }
        public virtual DbSet<Hash> Hash { get; set; }
        public virtual DbSet<Job> Job { get; set; }
        public virtual DbSet<JobQueue> JobQueue { get; set; }
        public virtual DbSet<JobParameter> JobParameter { get; set; }
        public virtual DbSet<List> List { get; set; }
        public virtual DbSet<Schema> Schema { get; set; }
        public virtual DbSet<Server> Server { get; set; }
        public virtual DbSet<Set> Set { get; set; }
        public virtual DbSet<State> State { get; set; }
        public virtual DbSet<MechanicBinding> MechanicBinding { get; set; }
        public virtual DbSet<InitialControlSchedule> InitialControlSchedule { get; set; }
        public virtual DbSet<FuelSOCAR> FuelSOCAR { get; set; }
        public virtual DbSet<RouteDailyKM> RouteDailyKM { get; set; }
        public virtual DbSet<Depots> Depots { get; set; }
        public virtual DbSet<JobcardToTroubleshoot> JobcardToTroubleshoot { get; set; }
        public virtual DbSet<TroubleShoot> TroubleShoot { get; set; }
        public virtual DbSet<Goods> Goods { get; set; }
        public virtual DbSet<WarehouseExits> WarehouseExits { get; set; }
        public virtual DbSet<WarehouseReceipts> WarehouseReceipts { get; set; }
        public virtual DbSet<TempWarehouse> TempWarehouse { get; set; }
        public virtual DbSet<Requisitions> Requisitions { get; set; }
        public virtual DbSet<MaintenanceHistory> MaintenanceHistory { get; set; }
        public virtual DbSet<MaintenanceType> MaintenanceType { get; set; }
        public virtual DbSet<Settings> Settings { get; set; }
        public virtual DbSet<WarehouseToMaintenance> WarehouseToMaintenance { get; set; }
        public virtual DbSet<DoneWorks> DoneWorks { get; set; }
        public virtual DbSet<JobCards> JobCards { get; set; }
        public virtual DbSet<JobcardToDoneWorks> JobcardToDoneWorks { get; set; }
        public virtual DbSet<JobcardNotes> JobcardNotes { get; set; }
        public virtual DbSet<CheckUpCard> CheckUpCard { get; set; }
        public virtual DbSet<Notifications> Notifications { get; set; }
        public virtual DbSet<NotMetRequisitions> NotMetRequisitions { get; set; }
    }
}
