//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoneWorks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DoneWorks()
        {
            this.JobcardToDoneWorks = new HashSet<JobcardToDoneWorks>();
        }
    
        public int Id { get; set; }
        public string WorkCode { get; set; }
        public string WorkName { get; set; }
        public Nullable<int> NormativeFactory { get; set; }
        public Nullable<int> NormativeBakubus { get; set; }
        public Nullable<int> VehicleBrandId { get; set; }
    
        public virtual VehiclesBrand VehiclesBrand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobcardToDoneWorks> JobcardToDoneWorks { get; set; }
    }
}
