//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employees()
        {
            this.MechanicBinding = new HashSet<MechanicBinding>();
            this.MechanicBinding1 = new HashSet<MechanicBinding>();
            this.Users = new HashSet<Users>();
            this.InitialControlSchedule = new HashSet<InitialControlSchedule>();
            this.InitialControlSchedule1 = new HashSet<InitialControlSchedule>();
            this.InitialControlSchedule2 = new HashSet<InitialControlSchedule>();
            this.InitialControlSchedule3 = new HashSet<InitialControlSchedule>();
            this.InitialControlSchedule4 = new HashSet<InitialControlSchedule>();
            this.InitialControlSchedule5 = new HashSet<InitialControlSchedule>();
            this.JobCards = new HashSet<JobCards>();
            this.JobCards1 = new HashSet<JobCards>();
            this.JobCards2 = new HashSet<JobCards>();
            this.JobcardToDoneWorks = new HashSet<JobcardToDoneWorks>();
            this.JobcardToDoneWorks1 = new HashSet<JobcardToDoneWorks>();
            this.CheckUpCard = new HashSet<CheckUpCard>();
        }
    
        public int Id { get; set; }
        public string EmployeeCode { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string FutherName { get; set; }
        public Nullable<System.DateTime> RecruitmentDate { get; set; }
        public Nullable<System.DateTime> DeactivationDate { get; set; }
        public string Phone { get; set; }
        public string LicenceSeries { get; set; }
        public string LicenceNumber { get; set; }
        public string LicenceCategory { get; set; }
        public Nullable<System.DateTime> LicenceIssueDate { get; set; }
        public Nullable<System.DateTime> LicenceExpireDate { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> SectorId { get; set; }
        public Nullable<int> PositionId { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
    
        public virtual Departments Departments { get; set; }
        public virtual Positions Positions { get; set; }
        public virtual Sectors Sectors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MechanicBinding> MechanicBinding { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MechanicBinding> MechanicBinding1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users> Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InitialControlSchedule> InitialControlSchedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InitialControlSchedule> InitialControlSchedule1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InitialControlSchedule> InitialControlSchedule2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InitialControlSchedule> InitialControlSchedule3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InitialControlSchedule> InitialControlSchedule4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InitialControlSchedule> InitialControlSchedule5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobCards> JobCards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobCards> JobCards1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobCards> JobCards2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobcardToDoneWorks> JobcardToDoneWorks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobcardToDoneWorks> JobcardToDoneWorks1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckUpCard> CheckUpCard { get; set; }
    }
}
