//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuelSOCAR
    {
        public int Id { get; set; }
        public Nullable<int> InitContId { get; set; }
        public Nullable<System.DateTime> DateSOCAR { get; set; }
        public Nullable<decimal> FuelAmount1 { get; set; }
        public Nullable<decimal> FuelAmount2 { get; set; }
        public Nullable<decimal> FuelAmount3 { get; set; }
        public Nullable<System.TimeSpan> FuelTime1 { get; set; }
        public Nullable<System.TimeSpan> FuelTime2 { get; set; }
        public Nullable<System.TimeSpan> FuelTime3 { get; set; }
        public Nullable<int> AddedUserId { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
    
        public virtual InitialControlSchedule InitialControlSchedule { get; set; }
        public virtual Users Users { get; set; }
    }
}
