//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string InternalCode { get; set; }
        public string AnalogCode1 { get; set; }
        public string AnalogCode2 { get; set; }
        public string Name { get; set; }
    }
}
