//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InitialControlSchedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InitialControlSchedule()
        {
            this.FuelSOCAR = new HashSet<FuelSOCAR>();
            this.MaintenanceHistory = new HashSet<MaintenanceHistory>();
            this.CheckUpCard = new HashSet<CheckUpCard>();
        }
    
        public int Id { get; set; }
        public Nullable<int> VehicleId { get; set; }
        public Nullable<bool> IsOpen { get; set; }
        public Nullable<int> LeavingRecMechId { get; set; }
        public Nullable<int> LeavingSeniorRecMechId { get; set; }
        public Nullable<System.DateTime> LeavingTime { get; set; }
        public Nullable<decimal> LeavingKilometer { get; set; }
        public Nullable<decimal> LeavingFuel { get; set; }
        public Nullable<int> EnterRecMechId { get; set; }
        public Nullable<int> EnterSeniorRecMechId { get; set; }
        public Nullable<System.DateTime> EnterTime { get; set; }
        public Nullable<decimal> EnterKilometer { get; set; }
        public Nullable<decimal> EnterFuel { get; set; }
        public Nullable<int> FirstDriverId { get; set; }
        public Nullable<int> SecondDriverId { get; set; }
        public Nullable<int> RouteId { get; set; }
        public string LeavingNote { get; set; }
        public string EnterNote { get; set; }
        public Nullable<int> LeavingUpdateEmpId { get; set; }
        public Nullable<System.DateTime> LeavingUpdateDate { get; set; }
        public Nullable<int> EnterUpdateEmpId { get; set; }
        public Nullable<System.DateTime> EnterUpdateDate { get; set; }
        public Nullable<int> AllUpdateUserId { get; set; }
        public Nullable<System.DateTime> AllUpdateDate { get; set; }
        public Nullable<decimal> RouteLength { get; set; }
        public Nullable<decimal> FirstDrvKm { get; set; }
        public Nullable<decimal> FirstDrvFuel { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Employees Employees1 { get; set; }
        public virtual Employees Employees2 { get; set; }
        public virtual Employees Employees3 { get; set; }
        public virtual Employees Employees4 { get; set; }
        public virtual Employees Employees5 { get; set; }
        public virtual Routes Routes { get; set; }
        public virtual Vehicles Vehicles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FuelSOCAR> FuelSOCAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaintenanceHistory> MaintenanceHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckUpCard> CheckUpCard { get; set; }
    }
}
