//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobcardToTroubleshoot
    {
        public int Id { get; set; }
        public Nullable<int> JobcardId { get; set; }
        public Nullable<int> TroubleshootId { get; set; }
    
        public virtual TroubleShoot TroubleShoot { get; set; }
    }
}
