//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobcardNotes
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<int> AddedUserId { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<int> JobCardId { get; set; }
    
        public virtual JobCards JobCards { get; set; }
        public virtual Users Users { get; set; }
    }
}
