//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobCards
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobCards()
        {
            this.JobcardToDoneWorks = new HashSet<JobcardToDoneWorks>();
            this.MaintenanceHistory = new HashSet<MaintenanceHistory>();
            this.Requisitions = new HashSet<Requisitions>();
            this.JobcardNotes = new HashSet<JobcardNotes>();
            this.NotMetRequisitions = new HashSet<NotMetRequisitions>();
            this.NotMetRequisitions1 = new HashSet<NotMetRequisitions>();
        }
    
        public int Id { get; set; }
        public Nullable<int> JobCardNo { get; set; }
        public Nullable<int> CheckupCardId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<bool> IsOpen { get; set; }
        public Nullable<bool> InUnderRepair { get; set; }
        public Nullable<bool> InWaitDepot { get; set; }
        public Nullable<bool> IsAccident { get; set; }
        public Nullable<bool> IsMaintenance { get; set; }
        public Nullable<bool> IsRepair { get; set; }
        public Nullable<bool> IsGuarantee { get; set; }
        public Nullable<bool> InWaitRoute { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<int> ReceivingServisOfficer { get; set; }
        public Nullable<int> TakeOverServisOfficer { get; set; }
        public Nullable<int> HandOverServisOfficer { get; set; }
        public string Note { get; set; }
        public Nullable<bool> CreatedBySystem { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<bool> TakeOverServisOfficerSubmit { get; set; }
    
        public virtual Companies Companies { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Employees Employees1 { get; set; }
        public virtual Employees Employees2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobcardToDoneWorks> JobcardToDoneWorks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaintenanceHistory> MaintenanceHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Requisitions> Requisitions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobcardNotes> JobcardNotes { get; set; }
        public virtual CheckUpCard CheckUpCard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotMetRequisitions> NotMetRequisitions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotMetRequisitions> NotMetRequisitions1 { get; set; }
    }
}
