//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceHistory
    {
        public int Id { get; set; }
        public Nullable<int> InitContId { get; set; }
        public Nullable<int> JobCardId { get; set; }
        public Nullable<int> MaintenanceId { get; set; }
        public Nullable<bool> MaintenanceStatus { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
    
        public virtual InitialControlSchedule InitialControlSchedule { get; set; }
        public virtual MaintenanceType MaintenanceType { get; set; }
        public virtual JobCards JobCards { get; set; }
    }
}
