//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notifications
    {
        public int Id { get; set; }
        public Nullable<int> NotificationTitleId { get; set; }
        public Nullable<int> DataId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> AddingDate { get; set; }
    
        public virtual NotificationTitles NotificationTitles { get; set; }
        public virtual Users Users { get; set; }
    }
}
