//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requisitions
    {
        public int Id { get; set; }
        public Nullable<int> JobCardId { get; set; }
        public Nullable<int> TempWarehouseId { get; set; }
        public Nullable<decimal> RequiredQuantity { get; set; }
        public Nullable<decimal> MeetingQuantity { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<bool> IsOpen { get; set; }
    
        public virtual TempWarehouse TempWarehouse { get; set; }
        public virtual JobCards JobCards { get; set; }
    }
}
