//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteDailyKM
    {
        public int Id { get; set; }
        public Nullable<int> RouteId { get; set; }
        public Nullable<decimal> KmLimit { get; set; }
    
        public virtual Routes Routes { get; set; }
    }
}
