//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseToMaintenance
    {
        public int Id { get; set; }
        public Nullable<int> MaintenanceTypeId { get; set; }
        public Nullable<int> WarehouseId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> NotRequireSPLimit { get; set; }
    
        public virtual MaintenanceType MaintenanceType { get; set; }
        public virtual TempWarehouse TempWarehouse { get; set; }
    }
}
